#!/usr/bin/env node

import fs from "fs";
import path from "path";
import { Command } from "commander";

const program = new Command()
  .name("generate-schema")
  .description("Generate Zod schemas from an OpenAPI spec")
  .option("--url <url>", "OpenAPI spec URL (base URL or full path)")
  .option("-o, --output <path>", "Output file path", "src/types/generated.ts")
  .parse();

const opts = program.opts();

let url: string = opts.url || "";
const output: string = opts.output;

if (!url) {
  url = process.env.API_URL
    ? `${process.env.API_URL}/openapi.json`
    : "http://localhost:8001/openapi.json";
} else if (!url.endsWith("/openapi.json") && !url.endsWith("/swagger/doc.json")) {
  url = url.replace(/\/$/, "") + "/openapi.json";
}

async function main() {
  console.log(`Fetching OpenAPI spec from ${url}...`);
  
  const res = await fetch(url);
  if (!res.ok) {
    console.error(`Failed to fetch spec: HTTP ${res.status}`);
    process.exit(1);
  }
  
  const spec = await res.json();
  const schemas = spec.components?.schemas || {};
  const paths = spec.paths || {};
  
  console.log(`Found ${Object.keys(paths).length} paths, ${Object.keys(schemas).length} schemas`);
  
  // Generate Zod schemas from OpenAPI schemas
  const lines: string[] = [
    "// Auto-generated by auth-ui-shared generate:schema — do not edit manually",
    "",
    'import { z } from "zod";',
    "",
  ];
  
  for (const [name, schema] of Object.entries(schemas) as any[]) {
    const zodSchema = openapiToZod(name, schema);
    lines.push(`export const ${camelCase(name)}Schema = ${zodSchema};`);
    lines.push(`export type ${name} = z.infer<typeof ${camelCase(name)}Schema>;`);
    lines.push("");
  }
  
  const content = lines.join("\n");
  fs.mkdirSync(path.dirname(output), { recursive: true });
  fs.writeFileSync(output, content);
  console.log(`Generated types written to ${output}`);
}

export function camelCase(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

export function openapiToZod(name: string, schema: any): string {
  if (schema.allOf) {
    const parts = schema.allOf.map((s: any, i: number) => openapiToZod(`${name}AllOf${i}`, s));
    if (parts.length === 1) return applyModifiers(parts[0], schema);
    const merged = parts.reduce((acc: string, cur: string) => `${acc}.and(${cur})`);
    return applyModifiers(merged, schema);
  }

  if (schema.oneOf || schema.anyOf) {
    const variants: any[] = schema.oneOf || schema.anyOf;
    const parts = variants.map((s: any, i: number) => openapiToZod(`${name}Union${i}`, s));
    if (parts.length === 1) return applyModifiers(parts[0], schema);
    const inner = parts.join(", ");
    return applyModifiers(`z.union([${inner}])`, schema);
  }

  if (schema.enum) {
    const values = schema.enum.map((v: unknown) => JSON.stringify(v)).join(", ");
    return applyModifiers(`z.enum([${values}])`, schema);
  }

  if (schema.type === "string") {
    let base: string;
    if (schema.format === "email") base = "z.email()";
    else if (schema.format === "uuid") base = "z.uuid()";
    else if (schema.format === "date-time") base = "z.coerce.date()";
    else base = "z.string()";
    return applyModifiers(base, schema);
  }
  if (schema.type === "integer") return applyModifiers("z.number().int()", schema);
  if (schema.type === "number") return applyModifiers("z.number()", schema);
  if (schema.type === "boolean") return applyModifiers("z.boolean()", schema);
  if (schema.type === "array") {
    const items = schema.items ? openapiToZod(`${name}Item`, schema.items) : "z.any()";
    return applyModifiers(`z.array(${items})`, schema);
  }
  if (schema.type === "object" || schema.properties) {
    const props = schema.properties || {};
    const required: string[] = schema.required || [];
    const entries = Object.entries(props).map(([key, val]: any) => {
      const zod = openapiToZod(key, val);
      const isRequired = required.includes(key);
      return `${key}: ${isRequired ? zod : `${zod}.optional()`}`;
    });
    return applyModifiers(`z.object({ ${entries.join(", ")} })`, schema);
  }

  return applyModifiers("z.any()", schema);
}

function applyModifiers(base: string, schema: any): string {
  if (schema.nullable === true) {
    return `${base}.nullable()`;
  }
  return base;
}

main().catch(console.error);
